lexik_jwt_authentication:
    # Use a symmetric key in tests: no OpenSSL key files, no passphrases.
    secret_key: '%env(string:JWT_SECRET_KEY)%'
    encoder:
        signature_algorithm: HS256
    public_key: '%env(resolve:JWT_PUBLIC_KEY)%'
    pass_phrase: '%env(JWT_PASSPHRASE)%'
    token_ttl:    3600  # 1 hour
    user_identity_field: email
    token_extractors:
        authorization_header:
            enabled: true
            prefix: Bearer
            name: Authorization

