name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and start containers
        run: |
          docker compose -f docker-compose.yml build
          docker compose -f docker-compose.yml up -d

      - name: Install Composer dev dependencies inside backend container
        run: |
          docker compose exec -T backend sh -lc '
            set -e
            cd /var/www/app
            COMPOSER_ALLOW_SUPERUSER=1 composer install --prefer-dist --no-progress --no-interaction
          '

      - name: Run PHPUnit with coverage inside backend container
        run: |
          docker compose exec -T backend sh -lc '
            set -e
            cd /var/www/app
            APP_ENV=test XDEBUG_MODE=coverage php -d xdebug.mode=coverage vendor/bin/phpunit \
              -c phpunit.dist.xml \
              --coverage-clover var/coverage.xml \
              --coverage-text
          '


      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: backend/var/coverage.xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: backend/var/coverage.xml
          fail_ci_if_error: true
